//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreconceptportal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hours
    {
        public int UserId { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public Nullable<System.DateTime> ExtraHours { get; set; }
        public Nullable<System.DateTime> Hours1 { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual User User { get; set; }
    }
}
