//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreconceptportal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.UserProject = new HashSet<UserProject>();
        }
    
        public int UserId { get; set; }
        public string Name { get; set; }
        public Nullable<double> FareHour { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public Nullable<double> PriceHour { get; set; }
        public Nullable<double> FareExtraHour { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserProject> UserProject { get; set; }
    }
}
